version: '3.7'
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vladik12345
      - POSTGRES_DB=postgres
    volumes:
      - ./backend/postgres-data/postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    restart: always
    build:
      context: ./backend/
      dockerfile: dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  client:
    build:
      context: ./reactjs/
      dockerfile: dockerfile
    ports:
      - "28080:80"
    container_name: sn-client
    depends_on:
      - app