volumes:
  db_volume:

version: '3.7'
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vladik12345
      - POSTGRES_DB=postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - 1337:5000
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: [ "python", "main.py","runserver" ]